-- DROP TABLE IF EXISTS SOCIAL_COMMENTS;
-- DROP SEQUENCE IF EXISTS SOCIAL_COMMENTS_PK_SEQ;
CREATE SEQUENCE SOCIAL_COMMENTS_PK_SEQ;
CREATE TABLE SOCIAL_COMMENTS (
    ID BIGINT DEFAULT NEXTVAL('SOCIAL_COMMENTS_PK_SEQ'),
    BODY TEXT,
    PAYLOAD_CONTEXT_ID VARCHAR(250),
    USER_ID VARCHAR(100),
    TENANT_DOMAIN VARCHAR(100),
    LIKES SMALLINT,
    UNLIKES SMALLINT,
    TIMESTAMP VARCHAR(100), 
    PRIMARY KEY (ID)
);

-- DROP TABLE IF EXISTS SOCIAL_RATING;
-- DROP SEQUENCE IF EXISTS SOCIAL_RATING_PK_SEQ;
CREATE SEQUENCE SOCIAL_RATING_PK_SEQ;
CREATE TABLE SOCIAL_RATING (
    ID BIGINT DEFAULT NEXTVAL('SOCIAL_RATING_PK_SEQ'),
    COMMENT_ID BIGINT NOT NULL,
    PAYLOAD_CONTEXT_ID VARCHAR(250),
    USER_ID VARCHAR(100), 
    TENANT_DOMAIN VARCHAR(100),
    RATING SMALLINT,
    TIMESTAMP VARCHAR(100),
    PRIMARY KEY (ID),
    FOREIGN KEY (COMMENT_ID) REFERENCES SOCIAL_COMMENTS(ID) ON DELETE CASCADE
);

-- DROP TABLE IF EXISTS SOCIAL_RATING_CACHE;
CREATE TABLE SOCIAL_RATING_CACHE (
    PAYLOAD_CONTEXT_ID VARCHAR(250), 
    RATING_TOTAL INTEGER,
    RATING_COUNT INTEGER,
    RATING_AVERAGE DOUBLE PRECISION,
    TENANT_DOMAIN VARCHAR(100),
    PRIMARY KEY (PAYLOAD_CONTEXT_ID)
);

-- DROP TABLE IF EXISTS SOCIAL_LIKES;
-- DROP SEQUENCE IF EXISTS SOCIAL_LIKES_PK_SEQ;
CREATE SEQUENCE SOCIAL_LIKES_PK_SEQ;
CREATE TABLE SOCIAL_LIKES (
    ID BIGINT DEFAULT NEXTVAL('SOCIAL_LIKES_PK_SEQ'),
    PAYLOAD_CONTEXT_ID BIGINT NOT NULL,
    USER_ID VARCHAR(100),
    TENANT_DOMAIN VARCHAR(100),
    LIKE_VALUE SMALLINT,
    TIMESTAMP VARCHAR(100),
    PRIMARY KEY (ID),
    FOREIGN KEY (PAYLOAD_CONTEXT_ID) REFERENCES SOCIAL_COMMENTS(ID) ON DELETE CASCADE
);
