CREATE SEQUENCE APM_BUSINESS_OWNER_SEQUENCE START WITH 1 INCREMENT BY 1 ;

CREATE TABLE IF NOT EXISTS APM_BUSINESS_OWNER(

OWNER_ID INTEGER DEFAULT nextval('apm_business_owner_sequence'),

OWNER_NAME VARCHAR(200) NOT NULL,

OWNER_EMAIL VARCHAR(300) NOT NULL,

OWNER_DESC VARCHAR(1500),

OWNER_SITE VARCHAR(200),

TENANT_ID INTEGER,

PRIMARY KEY(OWNER_ID),

UNIQUE (OWNER_NAME,OWNER_EMAIL,TENANT_ID)

);



CREATE TABLE IF NOT EXISTS APM_STORE_FAVOURITE_PAGE (

ID INTEGER ,

USER_ID VARCHAR(50) NOT NULL,

TENANT_ID_OF_USER INTEGER NOT NULL,

TENANT_ID_OF_STORE INTEGER NOT NULL,

PRIMARY KEY (ID)

);